theme: jekyll-theme-cayman

# Documentation Page
This homepage will host documnetation of open projects hosted in MarcAzar Github

## <a href="bipbuffer.html">Bip Buffer</a>

## <a href="cyclichash.html">Cyclic-Polynomial-Hash</a>
### <a href="characterhash.html">Character HAsh</a>
